### ISSUE TITLE
Add to array using spread operator

### ISSUE THREAD

**Issue by jensjakob** [coopjakob/kenora-thistles#10]
What error message does this generate? I want to use spread operations. 

https://github.com/coopjakob/kenora-thistles/blob/0a64785d26c3191c8e062d73bbf5276e458177b5/src/components/ProductMatrix.vue#L141

**Comment by coopjakob** [comment]
Type 'any[]' is not assignable to type 'never[]'.
on first `this.productList`

**Comment by coopjakob** [comment]
```
    return {
      productList: [],
```

**Comment by coopjakob** [comment]
Works. Great! Thanks.

#15 seems like the next problem i relation to this
