### ISSUE TITLE
Other key than index?

### ISSUE THREAD

**Issue by jensjakob** [coopjakob/kenora-thistles#11]
These labels won't update after rendering, but maybe index shouldn't be used? Disable 
vue/require-v-for-key? 

https://github.com/coopjakob/kenora-thistles/blob/0a64785d26c3191c8e062d73bbf5276e458177b5/src/components/ProductCard.vue#L49

**Comment by coopjakob** [comment]
So, we go for unique keys even if the info is not going to be updated? More future proof I guess.

**Comment by coopjakob** [comment]
We currently use the full text as the key.
