### ISSUE TITLE
Regexp problem with 10:- /kg

### ISSUE THREAD

**Issue by coopjakob** [coopjakob/kenora-thistles#12]
`const regex = /(?<label>\d+ för )*(?<price>\d+):(?<decimal>[-\d]+) *\/*(?<unit>.*)/g;`

![Screenshot 2020-02-24 at 10 20 37](https://user-images.githubusercontent.com/59063397/75140532-66cb6680-56ef-11ea-9298-86cf58c2231a.png)
![Screenshot 2020-02-24 at 10 20 04](https://user-images.githubusercontent.com/59063397/75140539-67fc9380-56ef-11ea-80e9-5511369b3517.png)

Test on https://regex101.com/

**Comment by benjick** [comment]
What result do you want? I'm having some trouble figuring it out

**Comment by coopjakob** [comment]
![image](https://user-images.githubusercontent.com/59063397/75367828-2d4a5500-58c1-11ea-9570-bffa953d14ea.png)
Best design for now!?

**Comment by coopjakob** [comment]
Solved in e1c56089dda6f2d753bc494fc2cbe0145112f99d
