### ISSUE TITLE
Remove duplicated products

### ISSUE THREAD

**Issue by coopjakob** [coopjakob/kenora-thistles#15]
`this.productList = _.uniqBy(this.productList, 'code');`

https://github.com/coopjakob/kenora-thistles/blob/eaec4f821c46f94954e838ff70e149544e423f19/src/components/ProductMatrix.vue#L134

**Comment by benjick** [comment]
Native solution: `[...new Set(...this.productList, ...productsInResponse)]`

**Comment by coopjakob** [comment]
a08202c4a8ed0bb8f0df0e47c972b2ada75bbc5e
